from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Literal

from pydantic import BaseModel, Field

from clipradar.models import ClipCandidate


GEMINI_MODELS = [
    ("Gemini 3.8 Flash · highest quality", "gemini-3.8-flash"),
    ("Gemini 3.7 Flash · quality", "gemini-3.7-flash"),
    ("Gemini 3.5 Flash · balanced", "gemini-3.5-flash"),
    ("Gemini 3.5 Flash-Lite · lowest cost", "gemini-3.5-flash-lite"),
    ("Gemini 3.1 Flash-Lite · efficient", "gemini-3.1-flash-lite"),
    ("Gemini 2.5 Flash · legacy stable", "gemini-2.5-flash"),
]

GEMINI_MAX_ATTEMPTS = 2
_OUTPUT_TOKEN_LIMITS = (8192, 16384)
_FRAMING_OUTPUT_TOKEN_LIMITS = (2048, 4096)
_REFRAME_MODES = {"auto", "focus", "gaming_split", "center", "contain"}
GeminiEventCallback = Callable[[str, str], None]


class GeminiError(RuntimeError):
    def __init__(
        self,
        message: str,
        *,
        request_count: int = 0,
        responses_with_usage: int = 0,
        input_tokens: int = 0,
        output_tokens: int = 0,
        estimated_cost_eur: float = 0.0,
    ):
        super().__init__(message)
        self.request_count = request_count
        self.responses_with_usage = responses_with_usage
        self.input_tokens = input_tokens
        self.output_tokens = output_tokens
        self.estimated_cost_eur = estimated_cost_eur


class _StructuredOutputError(RuntimeError):
    def __init__(self, message: str, finish_reason: str = "", *, retryable: bool = True):
        super().__init__(message)
        self.finish_reason = finish_reason
        self.retryable = retryable


class ClipEvaluation(BaseModel):
    score: int = Field(ge=0, le=100)
    reason: str = Field(min_length=3, max_length=280)
    start_offset_seconds: float = Field(ge=0)
    # Gemini's Schema type supports `minimum`, but not JSON Schema's
    # `exclusiveMinimum` generated by Pydantic's gt= constraint. A zero value
    # remains safe because boundary normalization below enforces at least one
    # second and then the configured minimum clip duration.
    end_offset_seconds: float = Field(ge=0)
    works_without_context: bool
    hook: str = Field(default="", max_length=140)
    title: str = ""
    description: str = ""
    tags: list[str] = Field(default_factory=list)
    reframe_mode: Literal["focus", "gaming_split", "center", "contain"] = "focus"
    focus_x: int = Field(default=500, ge=0, le=1000)
    focus_y: int = Field(default=500, ge=0, le=1000)
    facecam_x: int = Field(default=0, ge=0, le=1000)
    facecam_y: int = Field(default=0, ge=0, le=1000)
    facecam_width: int = Field(default=0, ge=0, le=1000)
    facecam_height: int = Field(default=0, ge=0, le=1000)
    gameplay_present: bool = False
    gameplay_x: int = Field(default=0, ge=0, le=1000)
    gameplay_y: int = Field(default=0, ge=0, le=1000)
    gameplay_width: int = Field(default=0, ge=0, le=1000)
    gameplay_height: int = Field(default=0, ge=0, le=1000)
    hud_present: bool = False
    hud_x: int = Field(default=0, ge=0, le=1000)
    hud_y: int = Field(default=0, ge=0, le=1000)
    hud_width: int = Field(default=0, ge=0, le=1000)
    hud_height: int = Field(default=0, ge=0, le=1000)
    profile_matches: bool = True


class FramingEvaluation(BaseModel):
    reason: str = Field(min_length=3, max_length=280)
    reframe_mode: Literal["focus", "gaming_split", "center", "contain"] = "focus"
    focus_x: int = Field(default=500, ge=0, le=1000)
    focus_y: int = Field(default=500, ge=0, le=1000)
    facecam_present: bool = False
    facecam_x: int = Field(default=0, ge=0, le=1000)
    facecam_y: int = Field(default=0, ge=0, le=1000)
    facecam_width: int = Field(default=0, ge=0, le=1000)
    facecam_height: int = Field(default=0, ge=0, le=1000)
    gameplay_present: bool = False
    gameplay_x: int = Field(default=0, ge=0, le=1000)
    gameplay_y: int = Field(default=0, ge=0, le=1000)
    gameplay_width: int = Field(default=0, ge=0, le=1000)
    gameplay_height: int = Field(default=0, ge=0, le=1000)
    hud_present: bool = False
    hud_x: int = Field(default=0, ge=0, le=1000)
    hud_y: int = Field(default=0, ge=0, le=1000)
    hud_width: int = Field(default=0, ge=0, le=1000)
    hud_height: int = Field(default=0, ge=0, le=1000)
    profile_matches: bool = True


@dataclass(frozen=True, slots=True)
class EvaluationResult:
    score: int
    reason: str
    refined_start: float
    refined_end: float
    input_tokens: int
    output_tokens: int
    estimated_cost_eur: float
    request_count: int = 1
    title: str = ""
    description: str = ""
    tags: tuple[str, ...] = ()
    reframe_mode: str = "focus"
    focus_x: float = 0.5
    focus_y: float = 0.5
    facecam_x: float | None = None
    facecam_y: float | None = None
    facecam_width: float | None = None
    facecam_height: float | None = None
    gameplay_x: float | None = None
    gameplay_y: float | None = None
    gameplay_width: float | None = None
    gameplay_height: float | None = None
    hud_x: float | None = None
    hud_y: float | None = None
    hud_width: float | None = None
    hud_height: float | None = None
    profile_matches: bool = True


@dataclass(frozen=True, slots=True)
class FramingResult:
    reason: str
    reframe_mode: str
    focus_x: float
    focus_y: float
    facecam_x: float | None
    facecam_y: float | None
    facecam_width: float | None
    facecam_height: float | None
    input_tokens: int
    output_tokens: int
    estimated_cost_eur: float
    request_count: int = 1
    gameplay_x: float | None = None
    gameplay_y: float | None = None
    gameplay_width: float | None = None
    gameplay_height: float | None = None
    hud_x: float | None = None
    hud_y: float | None = None
    hud_width: float | None = None
    hud_height: float | None = None
    profile_matches: bool = True


class GeminiClient:
    def test_connection(self, api_key: str, model: str) -> str:
        if not api_key.strip():
            raise GeminiError("Enter a Gemini API key first.")
        try:
            from google import genai

            with genai.Client(api_key=api_key.strip()) as client:
                resolved = client.models.get(model=model)
            name = str(getattr(resolved, "display_name", None) or getattr(resolved, "name", model))
            return f"Connected · {name}"
        except Exception as exc:
            raise GeminiError(self._safe_message(exc, api_key)) from exc

    def analyze_candidate(
        self,
        *,
        api_key: str,
        model: str,
        preview_path: str | Path,
        candidate: ClipCandidate,
        source_duration: float,
        minimum_duration: float,
        maximum_duration: float,
        temperature: float,
        description_style: str = "Auto",
        metadata_language: str = "Auto",
        content_category: str | None = None,
        framing_guidance: str = "",
        selection_guidance: str = "",
        event_callback: GeminiEventCallback | None = None,
    ) -> EvaluationResult:
        preview_path = Path(preview_path)
        if not api_key.strip():
            raise GeminiError("No Gemini API key is configured. Open Settings → AI.")
        data = preview_path.read_bytes()
        if len(data) > 19 * 1024 * 1024:
            raise GeminiError("Candidate preview exceeds the safe inline upload limit.")
        prompt = self._prompt(
            candidate,
            minimum_duration,
            maximum_duration,
            description_style,
            metadata_language,
            content_category,
            framing_guidance,
            selection_guidance,
        )
        event_callback = event_callback or (lambda _message, _level: None)
        request_count = 0
        responses_with_usage = 0
        input_tokens = 0
        output_tokens = 0
        try:
            from google import genai
            from google.genai import types

            part = types.Part.from_bytes(data=data, mime_type="video/mp4")
            with genai.Client(api_key=api_key.strip()) as client:
                for attempt in range(GEMINI_MAX_ATTEMPTS):
                    request_count += 1
                    config = types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_schema=ClipEvaluation,
                        temperature=max(0.0, min(1.0, temperature)) if attempt == 0 else 0.0,
                        max_output_tokens=_OUTPUT_TOKEN_LIMITS[attempt],
                    )
                    retry_prompt = prompt
                    if attempt:
                        retry_prompt += (
                            "\nThis is a retry because the previous structured response was incomplete. "
                            "Return one complete, compact JSON object and keep the description under 900 characters."
                        )
                    response = client.models.generate_content(
                        model=model,
                        contents=[retry_prompt, part],
                        config=config,
                    )
                    usage = getattr(response, "usage_metadata", None)
                    if usage is not None:
                        responses_with_usage += 1
                    input_tokens += int(getattr(usage, "prompt_token_count", 0) or 0)
                    output_tokens += int(getattr(usage, "candidates_token_count", 0) or 0)
                    output_tokens += int(getattr(usage, "thoughts_token_count", 0) or 0)
                    try:
                        evaluation = self._parse_evaluation(response)
                        break
                    except _StructuredOutputError as exc:
                        if not exc.retryable:
                            reason = exc.finish_reason or "provider policy"
                            raise GeminiError(
                                f"Gemini stopped this candidate before completing it ({reason}).",
                                request_count=request_count,
                                responses_with_usage=responses_with_usage,
                                input_tokens=input_tokens,
                                output_tokens=output_tokens,
                                estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
                            ) from exc
                        if attempt + 1 >= GEMINI_MAX_ATTEMPTS:
                            reason = f" ({exc.finish_reason})" if exc.finish_reason else ""
                            raise GeminiError(
                                "Gemini returned an incomplete structured response"
                                f"{reason} twice. Please retry this video; no partial metadata was saved.",
                                request_count=request_count,
                                responses_with_usage=responses_with_usage,
                                input_tokens=input_tokens,
                                output_tokens=output_tokens,
                                estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
                            ) from exc
                        reason = f" · finish reason: {exc.finish_reason}" if exc.finish_reason else ""
                        event_callback(
                            "Gemini response was incomplete"
                            f"{reason}; retrying once with a larger output limit.",
                            "warning",
                        )
        except Exception as exc:
            if isinstance(exc, GeminiError):
                raise
            raise GeminiError(
                self._safe_message(exc, api_key),
                request_count=request_count,
                responses_with_usage=responses_with_usage,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
            ) from exc

        candidate_duration = candidate.end_seconds - candidate.start_seconds
        start_offset = min(candidate_duration, max(0.0, evaluation.start_offset_seconds))
        end_offset = min(candidate_duration, max(start_offset + 1.0, evaluation.end_offset_seconds))
        refined_start = candidate.start_seconds + start_offset
        refined_end = min(source_duration, candidate.start_seconds + end_offset)
        if refined_end - refined_start < minimum_duration:
            midpoint = (refined_start + refined_end) / 2
            refined_start = max(0, midpoint - minimum_duration / 2)
            refined_end = min(source_duration, refined_start + minimum_duration)
            refined_start = max(0, refined_end - minimum_duration)
        if refined_end - refined_start > maximum_duration:
            refined_end = refined_start + maximum_duration
        reason = evaluation.reason.strip()
        if evaluation.hook.strip():
            reason = f"{reason} · Hook: {evaluation.hook.strip()}"
        title = _clean_title(evaluation.title or evaluation.hook)
        description = _clean_description(evaluation.description)
        tags = tuple(_clean_tags(evaluation.tags))
        facecam = _normalize_facecam(evaluation)
        gameplay = _normalize_region_values(
            evaluation.gameplay_x,
            evaluation.gameplay_y,
            evaluation.gameplay_width,
            evaluation.gameplay_height,
            minimum_size=0.04,
        ) if evaluation.gameplay_present else (None, None, None, None)
        hud = _normalize_region_values(
            evaluation.hud_x,
            evaluation.hud_y,
            evaluation.hud_width,
            evaluation.hud_height,
            minimum_size=0.02,
        ) if evaluation.hud_present else (None, None, None, None)
        return EvaluationResult(
            score=evaluation.score,
            reason=reason[:420],
            refined_start=round(refined_start, 3),
            refined_end=round(refined_end, 3),
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
            request_count=request_count,
            title=title,
            description=description,
            tags=tags,
            reframe_mode=evaluation.reframe_mode,
            focus_x=evaluation.focus_x / 1000,
            focus_y=evaluation.focus_y / 1000,
            facecam_x=facecam[0],
            facecam_y=facecam[1],
            facecam_width=facecam[2],
            facecam_height=facecam[3],
            gameplay_x=gameplay[0],
            gameplay_y=gameplay[1],
            gameplay_width=gameplay[2],
            gameplay_height=gameplay[3],
            hud_x=hud[0],
            hud_y=hud[1],
            hud_width=hud[2],
            hud_height=hud[3],
            profile_matches=evaluation.profile_matches,
        )

    def analyze_framing(
        self,
        *,
        api_key: str,
        model: str,
        original_preview_path: str | Path,
        current_preview_path: str | Path | None,
        requested_mode: str,
        candidate: ClipCandidate,
        temperature: float,
        framing_guidance: str = "",
        event_callback: GeminiEventCallback | None = None,
    ) -> FramingResult:
        """Compare source and current render, then return a replacement framing plan only."""
        if requested_mode not in _REFRAME_MODES:
            raise GeminiError("Select a valid reframe mode.")
        if not api_key.strip():
            raise GeminiError("No Gemini API key is configured. Open Settings → AI.")
        original_data = Path(original_preview_path).read_bytes()
        current_data = Path(current_preview_path).read_bytes() if current_preview_path else b""
        if len(original_data) + len(current_data) > 19 * 1024 * 1024:
            raise GeminiError("The framing comparison previews exceed the safe inline upload limit.")

        prompt = self._framing_prompt(
            candidate,
            requested_mode,
            framing_guidance,
            source_only=current_preview_path is None,
        )
        event_callback = event_callback or (lambda _message, _level: None)
        request_count = 0
        responses_with_usage = 0
        input_tokens = 0
        output_tokens = 0
        try:
            from google import genai
            from google.genai import types

            original_part = types.Part.from_bytes(data=original_data, mime_type="video/mp4")
            current_part = (
                types.Part.from_bytes(data=current_data, mime_type="video/mp4")
                if current_data
                else None
            )
            with genai.Client(api_key=api_key.strip()) as client:
                for attempt in range(GEMINI_MAX_ATTEMPTS):
                    request_count += 1
                    config = types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_schema=FramingEvaluation,
                        temperature=max(0.0, min(1.0, temperature)) if attempt == 0 else 0.0,
                        max_output_tokens=_FRAMING_OUTPUT_TOKEN_LIMITS[attempt],
                    )
                    retry_prompt = prompt
                    if attempt:
                        retry_prompt += (
                            "\nThe previous structured response was incomplete. Return one complete, compact "
                            "JSON object containing only the requested framing fields."
                        )
                    contents = [retry_prompt, original_part]
                    if current_part is not None:
                        contents.append(current_part)
                    response = client.models.generate_content(
                        model=model,
                        contents=contents,
                        config=config,
                    )
                    usage = getattr(response, "usage_metadata", None)
                    if usage is not None:
                        responses_with_usage += 1
                    input_tokens += int(getattr(usage, "prompt_token_count", 0) or 0)
                    output_tokens += int(getattr(usage, "candidates_token_count", 0) or 0)
                    output_tokens += int(getattr(usage, "thoughts_token_count", 0) or 0)
                    try:
                        evaluation = self._parse_framing(response)
                        break
                    except _StructuredOutputError as exc:
                        if not exc.retryable:
                            reason = exc.finish_reason or "provider policy"
                            raise GeminiError(
                                f"Gemini stopped the framing analysis before completing it ({reason}).",
                                request_count=request_count,
                                responses_with_usage=responses_with_usage,
                                input_tokens=input_tokens,
                                output_tokens=output_tokens,
                                estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
                            ) from exc
                        if attempt + 1 >= GEMINI_MAX_ATTEMPTS:
                            reason = f" ({exc.finish_reason})" if exc.finish_reason else ""
                            raise GeminiError(
                                "Gemini returned an incomplete framing response"
                                f"{reason} twice. The existing clip was kept unchanged.",
                                request_count=request_count,
                                responses_with_usage=responses_with_usage,
                                input_tokens=input_tokens,
                                output_tokens=output_tokens,
                                estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
                            ) from exc
                        event_callback(
                            "Gemini framing response was incomplete; retrying once with a larger output limit.",
                            "warning",
                        )
        except Exception as exc:
            if isinstance(exc, GeminiError):
                raise
            raise GeminiError(
                self._safe_message(exc, api_key),
                request_count=request_count,
                responses_with_usage=responses_with_usage,
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
            ) from exc

        mode = evaluation.reframe_mode if requested_mode == "auto" else requested_mode
        facecam = _normalize_facecam_values(
            evaluation.facecam_x,
            evaluation.facecam_y,
            evaluation.facecam_width,
            evaluation.facecam_height,
        )
        gameplay = _normalize_region_values(
            evaluation.gameplay_x,
            evaluation.gameplay_y,
            evaluation.gameplay_width,
            evaluation.gameplay_height,
            minimum_size=0.04,
        ) if evaluation.gameplay_present else (None, None, None, None)
        hud = _normalize_region_values(
            evaluation.hud_x,
            evaluation.hud_y,
            evaluation.hud_width,
            evaluation.hud_height,
            minimum_size=0.02,
        ) if evaluation.hud_present else (None, None, None, None)
        if mode == "gaming_split" and (not evaluation.facecam_present or facecam[0] is None):
            if requested_mode == "auto":
                mode = "focus"
                facecam = (None, None, None, None)
            else:
                raise GeminiError(
                    "Gemini could not locate a valid facecam region for Facecam + gameplay. "
                    "The existing clip was kept unchanged.",
                    request_count=request_count,
                    responses_with_usage=responses_with_usage,
                    input_tokens=input_tokens,
                    output_tokens=output_tokens,
                    estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
                )
        elif mode != "gaming_split":
            facecam = (None, None, None, None)
            gameplay = (None, None, None, None)
            hud = (None, None, None, None)
        return FramingResult(
            reason=evaluation.reason.strip()[:280],
            reframe_mode=mode,
            focus_x=evaluation.focus_x / 1000,
            focus_y=evaluation.focus_y / 1000,
            facecam_x=facecam[0],
            facecam_y=facecam[1],
            facecam_width=facecam[2],
            facecam_height=facecam[3],
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            estimated_cost_eur=estimate_cost_eur(model, input_tokens, output_tokens),
            request_count=request_count,
            gameplay_x=gameplay[0],
            gameplay_y=gameplay[1],
            gameplay_width=gameplay[2],
            gameplay_height=gameplay[3],
            hud_x=hud[0],
            hud_y=hud[1],
            hud_width=hud[2],
            hud_height=hud[3],
            profile_matches=evaluation.profile_matches,
        )

    @staticmethod
    def _parse_framing(response: object) -> FramingEvaluation:
        finish_reason = _finish_reason(response)
        if finish_reason and finish_reason != "STOP":
            blocked = finish_reason in {
                "SAFETY", "RECITATION", "BLOCKLIST", "PROHIBITED_CONTENT", "SPII",
            }
            raise _StructuredOutputError(
                "Gemini did not complete the framing response.",
                finish_reason,
                retryable=not blocked,
            )
        parsed = getattr(response, "parsed", None)
        if isinstance(parsed, FramingEvaluation):
            return parsed
        if parsed is not None:
            try:
                return FramingEvaluation.model_validate(parsed)
            except Exception:
                pass
        try:
            text = str(getattr(response, "text", "") or "").strip()
        except Exception:
            text = ""
        if text.startswith("```"):
            lines = text.splitlines()
            lines = lines[1:] if lines and lines[0].startswith("```") else lines
            lines = lines[:-1] if lines and lines[-1].strip() == "```" else lines
            text = "\n".join(lines).strip()
        try:
            return FramingEvaluation.model_validate(json.loads(text))
        except Exception as exc:
            raise _StructuredOutputError(
                "Gemini returned malformed or truncated framing JSON.",
                finish_reason,
            ) from exc

    @staticmethod
    def _framing_prompt(
        candidate: ClipCandidate,
        requested_mode: str,
        framing_guidance: str = "",
        *,
        source_only: bool = False,
    ) -> str:
        target = {
            "auto": (
                "Automatic fallback: choose focus, gaming_split, contain, or center based on what keeps the "
                "meaningful visual context throughout the clip."
            ),
            "focus": (
                "Important subject: independently reconsider what person, object, reaction, or gameplay action "
                "is actually important. Place focus_x/focus_y on that subject instead of assuming the old focus "
                "or geometric center was correct."
            ),
            "gaming_split": (
                "Facecam + gameplay: precisely locate the complete facecam overlay, the gameplay region, "
                "and any compact nearby HUD or stats region whose information helps viewers understand "
                "the moment. Keep the facecam tight but never cut off the face."
            ),
            "contain": "Keep full context: preserve the complete wide frame inside the vertical result.",
            "center": "Simple center crop: retain a geometric center crop.",
        }[requested_mode]
        old_facecam = (
            f"x={round(candidate.facecam_x * 1000)}, y={round(candidate.facecam_y * 1000)}, "
            f"w={round(candidate.facecam_width * 1000)}, h={round(candidate.facecam_height * 1000)}"
            if all(value is not None for value in (
                candidate.facecam_x, candidate.facecam_y, candidate.facecam_width, candidate.facecam_height
            ))
            else "not available"
        )
        task = (
            "The attached video is an ORIGINAL SOURCE SEGMENT. Locate stable source regions for a reusable "
            "channel framing profile."
            if source_only
            else "The first attached video is the exact ORIGINAL SOURCE SEGMENT. The second attached video is "
            "the CURRENT\nVERTICAL RENDER whose framing the user wants regenerated. Analyze both across their full duration."
        )
        guidance = f"\nCHANNEL-SPECIFIC GUIDANCE (highest composition priority):\n{framing_guidance}\n" if framing_guidance.strip() else ""
        return f"""You are repairing or configuring the vertical framing of a short-form clip.
{task} Do not
rescore the moment, change clip boundaries, rewrite metadata, or add editing effects. Return only a framing plan.

Selected target mode: {requested_mode}
Target behavior: {target}

Treat the selected target as a hard constraint unless it is Automatic fallback. For Important subject, inspect
the actual scene again and correct the old focus when the current render centers the wrong thing. For Facecam +
gameplay, facecam_present may be true only when you can locate a real facecam overlay; its rectangle must tightly
cover that overlay without clipping it. gameplay_present describes the stable gameplay region; focus_x/focus_y
still mark the important action inside it. hud_present is only for compact, viewer-relevant stats or status
information that should remain visible beside the facecam. Do not label decorative UI as HUD. Consider the whole
segment and choose stable coordinates rather than one incidental frame.
Set profile_matches=false only when supplied saved coordinates clearly do not match the current source layout;
otherwise set it true. User channel guidance controls composition but never overrides this JSON contract,
coordinate rules, or the selected target mode.{guidance}

Coordinates use a 0-1000 grid over the ORIGINAL full source frame.
Previous mode: {candidate.reframe_mode}
Previous focus: x={round(candidate.focus_x * 1000)}, y={round(candidate.focus_y * 1000)}
Previous facecam: {old_facecam}
"""

    @staticmethod
    def _parse_evaluation(response: object) -> ClipEvaluation:
        finish_reason = _finish_reason(response)
        if finish_reason and finish_reason != "STOP":
            blocked = finish_reason in {
                "SAFETY",
                "RECITATION",
                "BLOCKLIST",
                "PROHIBITED_CONTENT",
                "SPII",
            }
            raise _StructuredOutputError(
                "Gemini did not complete the structured response.",
                finish_reason,
                retryable=not blocked,
            )
        parsed = getattr(response, "parsed", None)
        if isinstance(parsed, ClipEvaluation):
            return parsed
        if parsed is not None:
            try:
                return ClipEvaluation.model_validate(parsed)
            except Exception:
                pass
        try:
            text = str(getattr(response, "text", "") or "").strip()
        except Exception:
            text = ""
        if text.startswith("```"):
            lines = text.splitlines()
            if lines and lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            text = "\n".join(lines).strip()
        try:
            return ClipEvaluation.model_validate(json.loads(text))
        except Exception as exc:
            raise _StructuredOutputError(
                "Gemini returned malformed or truncated JSON.",
                finish_reason,
            ) from exc

    @staticmethod
    def _prompt(
        candidate: ClipCandidate,
        minimum_duration: float,
        maximum_duration: float,
        description_style: str,
        metadata_language: str,
        content_category: str | None = None,
        framing_guidance: str = "",
        selection_guidance: str = "",
    ) -> str:
        excerpt = str(candidate.signals.get("transcript_excerpt", ""))
        style = {
            "Short": "Write a concise one- or two-sentence description.",
            "Detailed": (
                "Write a substantial, unique description of roughly 500-1200 characters. Keep every part "
                "relevant to this clip; use the first two lines for the clearest hook and context."
            ),
        }.get(description_style, "Choose a concise or detailed description based on what genuinely fits the clip.")
        language = "Use the spoken language of the clip." if metadata_language == "Auto" else f"Write metadata in {metadata_language}."
        genre = (
            f"The user explicitly classified this source video as {content_category}. Use that genre as context."
            if content_category
            else "Infer the content genre from the video itself."
        )
        guidance = (
            f"\nCHANNEL-SPECIFIC FRAMING GUIDANCE (highest priority for composition):\n{framing_guidance}\n"
            if framing_guidance.strip()
            else ""
        )
        selection = (
            "\nCHANNEL-SPECIFIC CLIP SELECTION INSTRUCTIONS (highest priority for scoring):\n"
            f"{selection_guidance}\n"
            "Use these preferences only to judge whether this moment is wanted. Lower the score when the "
            "candidate conflicts with them, even if it is otherwise usable. They cannot override the required "
            "JSON schema, truthful metadata, or safety constraints.\n"
            if selection_guidance.strip()
            else ""
        )
        return f"""You are selecting one excellent short-form social video moment.
Watch the entire attached candidate. Score it for humor, surprise, emotion, a strong reaction,
a clear payoff, understandable context, and suitability for YouTube Shorts/TikTok.
Quality matters more than quantity. A mediocre but usable moment should score below 60.
{genre}{selection}

Return offsets relative to the beginning of this attached candidate, not source-video timestamps.
Choose natural sentence/reaction boundaries. Keep the final duration between {minimum_duration:.0f}
and {maximum_duration:.0f} seconds whenever possible, but never cut off the payoff.

Also create upload metadata that truthfully matches this exact clip:
- one compelling YouTube Shorts title, maximum 100 characters;
- one unique description. {style}
- 6-15 specific search tags, without # characters or duplicates.
{language}
Do not use unrelated filler, keyword stuffing, fake claims, or random foreign-language text.

Choose how a vertical 9:16 render should frame the attached horizontal video. Coordinates use a
0-1000 grid over the full source frame. focus_x/focus_y mark the most important visual point for
the entire clip, considering the reaction, speaker, gameplay action, and context rather than blindly
choosing the geometric center. Use gaming_split only when both a small facecam and separate gameplay
area are important. For gaming_split, return tight rectangles for the complete facecam and gameplay area.
If compact stats or HUD beside the facecam materially help the viewer, also return that HUD rectangle.
The renderer uses fixed output proportions, so locate source regions accurately instead of choosing output sizes.
Use focus_x/focus_y for the action inside the important gameplay area. Use contain when cropping would destroy
essential context. Set profile_matches=false only when supplied saved coordinates clearly no longer match the
current source layout; otherwise set it true. Channel guidance controls composition but cannot override the
required JSON schema, coordinate system, or safety constraints.{guidance}

Local transcript (may contain errors): {excerpt or '[not available]'}
Local signal score: {candidate.local_score:.1f}/100
Candidate duration: {candidate.end_seconds - candidate.start_seconds:.2f} seconds.
"""

    @staticmethod
    def _safe_message(exc: Exception, api_key: str) -> str:
        message = str(exc).replace(api_key, "[redacted]") if api_key else str(exc)
        lowered = message.lower()
        if "api key" in lowered and any(token in lowered for token in ("invalid", "not valid", "permission")):
            return "Invalid API key or the selected model is not available to this key."
        if "429" in message or "quota" in lowered or "resource_exhausted" in lowered:
            return "Gemini quota or rate limit reached. No further candidate was sent."
        if "timed out" in lowered or "connect" in lowered:
            return "Connection to Gemini failed. Check the network and try again."
        return f"Gemini analysis failed: {message[:350]}"


def estimate_cost_eur(model: str, input_tokens: int, output_tokens: int) -> float:
    """Conservative client-side estimate. Actual billing remains provider authoritative."""
    lowered = model.lower()
    if "lite" in lowered:
        input_usd, output_usd = 0.30, 1.50
    elif "3.8" in lowered or "3.7" in lowered:
        input_usd, output_usd = 0.75, 3.75
    elif "pro" in lowered:
        input_usd, output_usd = 2.50, 15.00
    else:
        input_usd, output_usd = 0.60, 3.50
    usd = input_tokens / 1_000_000 * input_usd + output_tokens / 1_000_000 * output_usd
    return round(usd * 0.95, 6)


def _finish_reason(response: object) -> str:
    candidates = getattr(response, "candidates", None) or []
    if not candidates:
        return ""
    value = getattr(candidates[0], "finish_reason", None)
    if value is None:
        return ""
    raw = getattr(value, "value", value)
    return str(raw).rsplit(".", 1)[-1].upper()


def _clean_title(value: str) -> str:
    return " ".join(value.replace("\n", " ").split())[:100].strip()


def _clean_description(value: str) -> str:
    lines = [" ".join(line.split()) for line in value.replace("\r", "").split("\n")]
    cleaned = "\n".join(line for line in lines if line).strip()
    return cleaned[:5000]


def _clean_tags(values: list[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    total = 0
    for raw in values:
        tag = " ".join(str(raw).replace("#", " ").split()).strip(" ,")[:60]
        key = tag.casefold()
        if not tag or key in seen:
            continue
        projected = total + len(tag) + (1 if result else 0)
        if projected > 450:
            break
        seen.add(key)
        result.append(tag)
        total = projected
        if len(result) >= 15:
            break
    return result


def _normalize_facecam(evaluation: ClipEvaluation) -> tuple[float | None, float | None, float | None, float | None]:
    return _normalize_facecam_values(
        evaluation.facecam_x,
        evaluation.facecam_y,
        evaluation.facecam_width,
        evaluation.facecam_height,
    )


def _normalize_facecam_values(
    raw_x: int,
    raw_y: int,
    raw_width: int,
    raw_height: int,
) -> tuple[float | None, float | None, float | None, float | None]:
    return _normalize_region_values(raw_x, raw_y, raw_width, raw_height, minimum_size=0.06)


def _normalize_region_values(
    raw_x: int,
    raw_y: int,
    raw_width: int,
    raw_height: int,
    *,
    minimum_size: float,
) -> tuple[float | None, float | None, float | None, float | None]:
    values = (raw_x / 1000, raw_y / 1000, raw_width / 1000, raw_height / 1000)
    x, y, width, height = values
    if width < minimum_size or height < minimum_size or x + width > 1.01 or y + height > 1.01:
        return None, None, None, None
    return x, y, width, height
